# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instiz', models.CharField(blank=True, max_length=200)),
                ('link_instiz', models.URLField(blank=True)),
                ('clien', models.CharField(blank=True, max_length=200)),
                ('link_clien', models.URLField(blank=True)),
                ('fmkorea', models.CharField(blank=True, max_length=200)),
                ('link_fmkorea', models.URLField(blank=True)),
                ('ou', models.CharField(blank=True, max_length=200)),
                ('link_ou', models.URLField(blank=True)),
                ('pan', models.CharField(blank=True, max_length=200)),
                ('link_pan', models.URLField(blank=True)),
                ('slr', models.CharField(blank=True, max_length=200)),
                ('link_slr', models.URLField(blank=True)),
                ('mlb', models.CharField(blank=True, max_length=200)),
                ('link_mlb', models.URLField(blank=True)),
                ('inben', models.CharField(blank=True, max_length=200)),
                ('link_inben', models.URLField(blank=True)),
                ('ruri', models.CharField(blank=True, max_length=200)),
                ('link_ruri', models.URLField(blank=True)),
                ('utde', models.CharField(blank=True, max_length=200)),
                ('link_utde', models.URLField(blank=True)),
                ('bobe', models.CharField(blank=True, max_length=200)),
                ('link_bobe', models.URLField(blank=True)),
                ('ygosu', models.CharField(blank=True, max_length=200)),
                ('link_ygosu', models.URLField(blank=True)),
                ('drip', models.CharField(blank=True, max_length=200)),
                ('link_drip', models.URLField(blank=True)),
                ('theqoo', models.CharField(blank=True, max_length=200)),
                ('link_theqoo', models.URLField(blank=True)),
                ('dogge', models.CharField(blank=True, max_length=200)),
                ('link_dogge', models.URLField(blank=True)),
                ('namsung', models.CharField(blank=True, max_length=200)),
                ('link_namsung', models.URLField(blank=True)),
                ('flash1', models.CharField(blank=True, max_length=200)),
                ('link_flash1', models.URLField(blank=True)),
                ('flash2', models.CharField(blank=True, max_length=200)),
                ('link_flash2', models.URLField(blank=True)),
                ('dream1', models.CharField(blank=True, max_length=200)),
                ('link_dream1', models.URLField(blank=True)),
                ('dream2', models.CharField(blank=True, max_length=200)),
                ('link_dream2', models.URLField(blank=True)),
                ('bobe2', models.CharField(blank=True, max_length=200)),
                ('link_bobe2', models.URLField(blank=True)),
                ('fomos1', models.CharField(blank=True, max_length=200)),
                ('link_fomos1', models.URLField(blank=True)),
                ('fomos2', models.CharField(blank=True, max_length=200)),
                ('link_fomos2', models.URLField(blank=True)),
                ('ilbe', models.CharField(blank=True, max_length=200)),
                ('link_ilbe', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
